project:
  type: website

website:
  title: "waka-man.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/waka-man
      - icon: twitter
        href: https://twitter.com/WakumaTekalign
  twitter-card:
    creator: "@WakumaTekalign"
    site: https://waka-man.github.io
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

execute:
  freeze: auto
  



